name: durham-post-416-discord-bot
version: git
summary: durham-post-416-discord-bot
description: durham-post-416-discord-bot
base: core24
platforms:
  amd64:
  arm64:
confinement: strict
grade: stable

apps:
  durham-post-416-discord-bot:
    daemon: simple
    restart-condition: always
    command: bin/start.sh
    plugs:
      - network

parts:
  durham-post-416-discord-bot:
    source: .
    plugin: python
    python-packages:
      - discord
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp start.sh $CRAFT_PART_INSTALL/bin/
      cp app.py $CRAFT_PART_INSTALL/bin/
